// GENERATED by make_label_stubs.py — do not edit by hand.
// Regenerate after retraining with a different class set.
//
// Symptoms and treatments come from published agricultural extension
// sources. They have NOT been verified by an agronomist. Wrong
// chemical advice costs a farmer a season — have this reviewed
// before anyone acts on it.

class DiseaseInfo {
  final String crop;
  final String disease;
  final String symptoms;
  final String treatment;
  final String preHarvest;

  const DiseaseInfo({
    required this.crop,
    required this.disease,
    required this.symptoms,
    required this.treatment,
    required this.preHarvest,
  });
}

const Map<String, DiseaseInfo> labelLookup = {
  'Apple___Apple_scab': DiseaseInfo(
    crop: 'Apple',
    disease: 'Apple Scab',
    symptoms: 'Olive-green to brown velvety spots on leaves and fruit. Badly hit '
        'leaves yellow and drop early.',
    treatment: 'Spray a captan or mancozeb fungicide from bud break. Rake up and '
        'destroy fallen leaves — the fungus overwinters in them.',
    preHarvest: 'Wait 7 days after spraying before harvesting.',
  ),
  'Apple___Black_rot': DiseaseInfo(
    crop: 'Apple',
    disease: 'Black Rot',
    symptoms: 'Purple flecks on leaves that widen into brown spots with purple '
        'rims. Fruit rots from the blossom end in rings.',
    treatment: 'Prune out dead wood and cankers, which is where it survives. Spray '
        'captan or thiophanate-methyl at the labelled dose.',
    preHarvest: 'Wait 14 days after spraying before harvesting.',
  ),
  'Apple___Cedar_apple_rust': DiseaseInfo(
    crop: 'Apple',
    disease: 'Cedar Apple Rust',
    symptoms: 'Bright yellow-orange spots on the upper leaf surface, later with '
        'small tubes underneath.',
    treatment: 'Spray myclobutanil at pink bud stage. Remove nearby juniper or cedar '
        'where the fungus spends half its life cycle.',
    preHarvest: 'Wait 14 days after spraying before harvesting.',
  ),
  'Apple___healthy': DiseaseInfo(
    crop: 'Apple',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the orchard as usual.',
    preHarvest: '',
  ),
  'Blueberry___healthy': DiseaseInfo(
    crop: 'Blueberry',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Cherry_(including_sour)___Powdery_mildew': DiseaseInfo(
    crop: 'Cherry',
    disease: 'Powdery Mildew',
    symptoms: 'White powdery coating on leaves and shoots. Young leaves twist and '
        'stay small.',
    treatment: 'Spray sulphur or myclobutanil early, before the coating spreads. '
        'Thin the canopy so air moves through it.',
    preHarvest: 'Wait 7 days after spraying before harvesting.',
  ),
  'Cherry_(including_sour)___healthy': DiseaseInfo(
    crop: 'Cherry',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the orchard as usual.',
    preHarvest: '',
  ),
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': DiseaseInfo(
    crop: 'Maize',
    disease: 'Gray Leaf Spot',
    symptoms: 'Narrow rectangular grey-tan lesions running along the leaf veins.',
    treatment: 'Spray azoxystrobin or propiconazole at first sign. Rotate away from '
        'maize next season and bury crop residue.',
    preHarvest: 'Wait 30 days after spraying before harvesting.',
  ),
  'Corn_(maize)___Common_rust_': DiseaseInfo(
    crop: 'Maize',
    disease: 'Common Rust',
    symptoms: 'Small reddish-brown powdery pustules on both leaf surfaces. The '
        'powder rubs off on your hand.',
    treatment: 'Spray propiconazole if it appears before tasselling. Late infection '
        'on a mature crop rarely needs treatment.',
    preHarvest: 'Wait 30 days after spraying before harvesting.',
  ),
  'Corn_(maize)___Northern_Leaf_Blight': DiseaseInfo(
    crop: 'Maize',
    disease: 'Northern Leaf Blight',
    symptoms: 'Long grey-green cigar-shaped lesions, often starting on the lower '
        'leaves.',
    treatment: 'Spray azoxystrobin or propiconazole. Plough in residue after harvest '
        '— the fungus survives on it.',
    preHarvest: 'Wait 30 days after spraying before harvesting.',
  ),
  'Corn_(maize)___healthy': DiseaseInfo(
    crop: 'Maize',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Grape___Black_rot': DiseaseInfo(
    crop: 'Grape',
    disease: 'Black Rot',
    symptoms: 'Small tan leaf spots with dark borders. Berries shrivel into hard '
        'black mummies.',
    treatment: 'Spray mancozeb or myclobutanil from early shoot growth. Remove '
        'mummified berries — they carry it to next season.',
    preHarvest: 'Wait 14 days after spraying before harvesting.',
  ),
  'Grape___Esca_(Black_Measles)': DiseaseInfo(
    crop: 'Grape',
    disease: 'Esca (Black Measles)',
    symptoms: 'Yellow or red stripes between leaf veins. Berries get small dark '
        'spots. Whole vines can collapse suddenly.',
    treatment: 'No effective spray exists. Cut out affected wood well below the '
        'symptoms and protect large pruning cuts.',
    preHarvest: '',
  ),
  'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': DiseaseInfo(
    crop: 'Grape',
    disease: 'Leaf Blight',
    symptoms: 'Irregular dark brown patches on leaves, which dry and drop early.',
    treatment: 'Spray mancozeb. Improve air movement by thinning shoots and keeping '
        'the canopy off the ground.',
    preHarvest: 'Wait 14 days after spraying before harvesting.',
  ),
  'Grape___healthy': DiseaseInfo(
    crop: 'Grape',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the vineyard as usual.',
    preHarvest: '',
  ),
  'Orange___Haunglongbing_(Citrus_greening)': DiseaseInfo(
    crop: 'Orange',
    disease: 'Citrus Greening (HLB)',
    symptoms: 'Blotchy yellow mottling that is NOT the same on both sides of the '
        'midrib. Fruit stays small, green and lopsided, and tastes bitter.',
    treatment: 'There is no cure. Remove and destroy infected trees so they stop '
        'feeding the psyllid insect that spreads it, and control that insect '
        'on healthy trees. Plant only certified disease-free stock.',
    preHarvest: '',
  ),
  'Peach___Bacterial_spot': DiseaseInfo(
    crop: 'Peach',
    disease: 'Bacterial Spot',
    symptoms: 'Small dark angular leaf spots that fall out leaving shot holes. '
        'Fruit gets sunken cracked pits.',
    treatment: 'Spray copper early in the season, at low rates — high rates burn '
        'peach leaves. Choose tolerant varieties when replanting.',
    preHarvest: 'Wait 7 days after spraying before harvesting.',
  ),
  'Peach___healthy': DiseaseInfo(
    crop: 'Peach',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the orchard as usual.',
    preHarvest: '',
  ),
  'Pepper,_bell___Bacterial_spot': DiseaseInfo(
    crop: 'Bell Pepper',
    disease: 'Bacterial Spot',
    symptoms: 'Small water-soaked spots turning dark brown with yellow halos, on '
        'leaves and fruit.',
    treatment: 'Spray copper with mancozeb. Use disease-free seed and avoid working '
        'among wet plants, which spreads it by hand.',
    preHarvest: 'Wait 3 days after spraying before harvesting.',
  ),
  'Pepper,_bell___healthy': DiseaseInfo(
    crop: 'Bell Pepper',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Potato___Early_blight': DiseaseInfo(
    crop: 'Potato',
    disease: 'Early Blight',
    symptoms: 'Dark spots with rings inside them, like a target. Appears on the '
        'older, lower leaves first.',
    treatment: 'Spray mancozeb or chlorothalonil at the dose on the label. Keep the '
        'plants well watered — stressed plants get infected more easily.',
    preHarvest: 'Wait 7 days after spraying before harvesting.',
  ),
  'Potato___Late_blight': DiseaseInfo(
    crop: 'Potato',
    disease: 'Late Blight',
    symptoms: 'Dark brown water-soaked patches on the leaves, with pale mould '
        'underneath. Spreads across a field within days in humid weather.',
    treatment: 'Spray metalaxyl combined with mancozeb at the labelled dose. Remove '
        'and destroy badly infected plants.',
    preHarvest: 'Wait 7 days after spraying before harvesting.',
  ),
  'Potato___healthy': DiseaseInfo(
    crop: 'Potato',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Raspberry___healthy': DiseaseInfo(
    crop: 'Raspberry',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Rice___Bacterial_blight': DiseaseInfo(
    crop: 'Rice',
    disease: 'Bacterial Leaf Blight',
    symptoms: 'Leaf edges turn yellow, then brown, and dry out starting from the '
        'tip. Young plants can wilt entirely.',
    treatment: 'Spray copper oxychloride. Drain standing water from the field and '
        'hold back urea — drainage and less nitrogen matter more than the '
        'spray here. Choose a resistant variety next season.',
    preHarvest: 'Wait 14 days after spraying before harvesting.',
  ),
  'Rice___Blast': DiseaseInfo(
    crop: 'Rice',
    disease: 'Rice Blast',
    symptoms: 'Eye-shaped spots on leaves — grey or white in the centre with brown '
        'edges. When it reaches the neck of the panicle, grains stay empty.',
    treatment: 'Spray a tricyclazole or isoprothiolane fungicide at the dose written '
        'on the label. Do not increase the dose, and avoid heavy nitrogen, '
        'which makes blast worse.',
    preHarvest: 'Wait 21 days after spraying before harvesting.',
  ),
  'Rice___Brown_spot': DiseaseInfo(
    crop: 'Rice',
    disease: 'Brown Spot',
    symptoms: 'Many small oval brown spots with grey centres, scattered over the '
        'leaves. Common on poor or nutrient-starved soil.',
    treatment: 'Correct the soil first — brown spot usually means too little potash. '
        'Apply MoP as recommended for your field. If spots keep spreading, '
        'spray mancozeb or propiconazole at the labelled dose.',
    preHarvest: 'Wait 21 days after spraying before harvesting.',
  ),
  'Rice___Tungro': DiseaseInfo(
    crop: 'Rice',
    disease: 'Tungro',
    symptoms: 'Leaves turn yellow to orange from the tip, plants stay short with '
        'few tillers. Patches of affected plants spread through the field.',
    treatment: 'Tungro is a virus spread by the green leafhopper — no spray cures an '
        'infected plant. Pull out and destroy affected hills early, control '
        'leafhoppers while plants are young, and plant a resistant variety '
        'next season.',
    preHarvest: '',
  ),
  'Soybean___healthy': DiseaseInfo(
    crop: 'Soybean',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Squash___Powdery_mildew': DiseaseInfo(
    crop: 'Squash',
    disease: 'Powdery Mildew',
    symptoms: 'White powdery patches on leaves and stems, spreading until leaves '
        'dry out.',
    treatment: 'Spray sulphur, potassium bicarbonate or myclobutanil at first sign. '
        'Do not water from overhead.',
    preHarvest: 'Wait 3 days after spraying before harvesting.',
  ),
  'Strawberry___Leaf_scorch': DiseaseInfo(
    crop: 'Strawberry',
    disease: 'Leaf Scorch',
    symptoms: 'Many small purple spots that merge until the leaf looks burnt at the '
        'edges.',
    treatment: 'Spray captan or myclobutanil. Remove old leaves after picking and '
        'space plants so they dry quickly.',
    preHarvest: 'Wait 3 days after spraying before harvesting.',
  ),
  'Strawberry___healthy': DiseaseInfo(
    crop: 'Strawberry',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
  'Tomato___Bacterial_spot': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Bacterial Spot',
    symptoms: 'Small dark water-soaked spots with yellow rings around them, on '
        'leaves and fruit.',
    treatment: 'Spray a copper-based product. Water at the base of the plant, not '
        'from above, and use clean seed.',
    preHarvest: 'Wait 3 days after spraying before harvesting.',
  ),
  'Tomato___Early_blight': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Early Blight',
    symptoms: 'Brown circular spots with rings, on the lower leaves first. Leaves '
        'yellow and drop.',
    treatment: 'Spray mancozeb at the labelled dose. Remove affected leaves and do '
        'not compost them.',
    preHarvest: 'Wait 5 days after spraying before harvesting.',
  ),
  'Tomato___Late_blight': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Late Blight',
    symptoms: 'Large dark water-soaked patches on leaves and stems, spreading '
        'quickly in cool humid weather.',
    treatment: 'Spray metalaxyl with mancozeb straight away. Remove infected plants '
        '— this disease can take a whole field in days.',
    preHarvest: 'Wait 7 days after spraying before harvesting.',
  ),
  'Tomato___Leaf_Mold': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Leaf Mould',
    symptoms: 'Pale yellow patches on the upper leaf surface with olive-green '
        'velvety mould directly underneath.',
    treatment: 'Spray chlorothalonil or mancozeb. Increase ventilation — this one '
        'thrives in still, humid air under cover.',
    preHarvest: 'Wait 5 days after spraying before harvesting.',
  ),
  'Tomato___Septoria_leaf_spot': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Septoria Leaf Spot',
    symptoms: 'Many small circular spots with grey centres and dark borders, '
        'starting low on the plant.',
    treatment: 'Spray chlorothalonil or mancozeb. Mulch the soil surface to stop '
        'spores splashing up onto the leaves.',
    preHarvest: 'Wait 5 days after spraying before harvesting.',
  ),
  'Tomato___Spider_mites Two-spotted_spider_mite': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Two-Spotted Spider Mite',
    symptoms: 'Fine pale speckling on leaves, with delicate webbing underneath. '
        'Leaves turn bronze and dry.',
    treatment: 'This is a mite, not a disease — fungicide will not help. Spray '
        'abamectin or a miticide, or use insecticidal soap for a light '
        'attack. Mites build up fastest in hot dry conditions.',
    preHarvest: 'Wait 3 days after spraying before harvesting.',
  ),
  'Tomato___Target_Spot': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Target Spot',
    symptoms: 'Brown spots with concentric rings on leaves, stems and fruit. Can '
        'look like early blight.',
    treatment: 'Spray chlorothalonil or azoxystrobin. Remove lower leaves touching '
        'the soil.',
    preHarvest: 'Wait 5 days after spraying before harvesting.',
  ),
  'Tomato___Tomato_Yellow_Leaf_Curl_Virus': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Yellow Leaf Curl Virus',
    symptoms: 'Leaves curl upward, turn yellow at the edges and stay small. Plants '
        'stop growing and set little fruit.',
    treatment: 'No spray cures a virus. Remove infected plants immediately and '
        'control whitefly, which carries it. Use resistant varieties and '
        'protect young seedlings under net.',
    preHarvest: '',
  ),
  'Tomato___Tomato_mosaic_virus': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Mosaic Virus',
    symptoms: 'Light and dark green mottling on leaves, which may be narrow or '
        'puckered.',
    treatment: 'No spray cures a virus. Remove infected plants and wash hands and '
        'tools — it spreads by touch. Do not smoke near tomatoes; it survives '
        'in tobacco.',
    preHarvest: '',
  ),
  'Tomato___healthy': DiseaseInfo(
    crop: 'Tomato',
    disease: 'Healthy',
    symptoms: 'No disease found on this leaf.',
    treatment: 'No treatment needed. Keep watching the field as usual.',
    preHarvest: '',
  ),
};

/// Falls back to a readable version of the raw label when no entry
/// exists yet, rather than showing the model's internal class name.
DiseaseInfo lookUp(String rawLabel) {
  final known = labelLookup[rawLabel];
  if (known != null) return known;

  final parts = rawLabel.split('___');
  return DiseaseInfo(
    crop: parts.isNotEmpty ? parts[0].replaceAll('_', ' ') : rawLabel,
    disease: parts.length > 1 ? parts[1].replaceAll('_', ' ') : 'Unknown',
    symptoms: 'We have not written details for this one yet.',
    treatment:
        'Please ask your local agriculture officer before applying anything.',
    preHarvest: '',
  );
}
